name: Release Jot Client

on:
  release:
    types: [created]

jobs:
  build:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Get release version
        id: get_version
        run: echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build for Linux (amd64)
        run: GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o jot-linux-amd64 ./cmd/jot
      
      - name: Build for Linux (386)
        run: GOOS=linux GOARCH=386 go build -ldflags="-s -w" -o jot-linux-386 ./cmd/jot

      - name: Build for macOS (amd64)
        run: GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o jot-darwin-amd64 ./cmd/jot

      - name: Build for macOS (arm64)
        run: GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o jot-darwin-arm64 ./cmd/jot

      - name: Build for Windows (amd64)
        run: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o jot-windows-amd64.exe ./cmd/jot

      - name: Generate SHA256 checksums
        run: |
          sha256sum jot-linux-amd64 > jot-linux-amd64.sha256
          sha256sum jot-linux-386 > jot-linux-386.sha256
          sha256sum jot-darwin-amd64 > jot-darwin-amd64.sha256
          sha256sum jot-darwin-arm64 > jot-darwin-arm64.sha256
          sha256sum jot-windows-amd64.exe > jot-windows-amd64.sha256
          cat *.sha256 > checksums.txt

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            jot-linux-amd64
            jot-linux-386
            jot-darwin-amd64
            jot-darwin-arm64
            jot-windows-amd64.exe
            checksums.txt
